name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set Up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.10.3"

    # Step 3: Initialize and Apply Terraform
    - name: Terraform Init and Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        terraform init
        terraform apply -auto-approve
        terraform output -json > tf_output.json

    - name: Parse EC2 Public IP
      id: parse_ip
      run: |
        echo "EC2_PUBLIC_IP=$(jq -r '.ec2_public_ip.value' tf_output.json)" >> $GITHUB_ENV

    - name: Retry SSH connection until ready
      run: |
        for i in {1..5}; do
          if nc -z -w5 ${{ env.EC2_PUBLIC_IP }} 22; then
            echo "SSH is ready!"
            break
          else
            echo "Waiting for SSH to become available..."
            sleep 30
          fi
        done

    # Step 4: Install Docker on EC2
    - name: SSH and Install Docker
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ env.EC2_PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          sudo yum update -y
          sudo yum install -y git docker
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker ec2-user

    # Step 5: Clone Repository and Build Docker Image
    - name: Clone Repo and Run Docker
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ env.EC2_PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd ~/
          git clone https://github.com/gmartinsnull/fastapi_demo.git
          cd ~/fastapi_demo
          docker build -t fastapi_demo .
          docker run -d -p 8000:80 fastapi_demo
